spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wdmms3838
  redis:
    host: 192.168.248.129 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.tulingxueyuan: debug

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tMx69sUe9JuHwTxw4si # 访问身份验证中用到用户标识
    accessKeySecret: kb2y0sTiWIADhw5g2uBtlfNBkqMj9G # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: tuling-zm # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    #callback:  # 文件上传成功后的回调地址
    dir:
      prefix: tulingmall/images/ # 上传文件夹路径前缀
